name: Waka Readme

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Generate Waka Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False" 
          SHOW_PROFILE_VIEWS: "False" 
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_TIMEZONE: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_LINES_OF_CODE: "True"
          LOCALE: "en"