name: Waka Readme

on:
  schedule:
    # Runs at 12am CST
    - cron: '0 16 * * *'
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      # https://github.com/anmol098/waka-readme-stats
      - name: Generate Waka Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_USERNAME: "readme-bot"
          COMMIT_MESSAGE: "Updated with Dev Metrics"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False" 
          SHOW_PROFILE_VIEWS: "False" 
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_UPDATED_DATE: "False"
          LOCALE: "en"
          SHOW_SHORT_INFO: "False"